---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: Creates directory to store test output
  file:
    path: /home/ubuntu/gjohn
    state: directory

- name: Creates directory to store test output
  shell: |
    cd /home/ubuntu/gjohn
    curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    chmod +x ./kubectl
    sudo mv ./kubectl /usr/local/bin/kubectl
    kubectl version --client
    curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    chmod +x minikube
    sudo mv minikube /usr/local/bin/
    minikube version
    sudo apt-get update -y &&  sudo apt-get install -y docker.io
    sudo docker version
    sudo usermod -aG docker $USER && newgrp docker
    minikube start --driver=docker
    minikube status
#- name: Creates directory
#  file:
#    path: ~/web
#    state: directory
#
#- name: Copy index test page
#  template:
#    src: "files/index.js"
#    dest: "~/web/index.js"
#
#- name: Executing node
#  shell: |
#    pm2 start ~/web/index.js -f
#    echo "which pm2"  > /home/ubuntu/gjohn/test_out
#    which pm2 >> /home/ubuntu/gjohn/test_out
#    echo "ls /home/ubuntu"  >> /home/ubuntu/gjohn/test_out
#    ls -al /home/ubuntu >> /home/ubuntu/gjohn/test_out
#    echo "which pm2"  >> /home/ubuntu/gjohn/test_out
#    which pm2 >> /home/ubuntu/gjohn/test_out
