Description: >
  Capstone Kubernetes Stack.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String
  EC2RootVol4Size:
    Description: EC2 Root Volume Size
    Type: String
    Default: 29
Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub Capstone-${ID}
      GroupDescription: Allow port 22, port 8000.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.medium
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: gjohn 
      ImageId: ami-0ee23bfc74a881de5
      BlockDeviceMappings:
        DeviceName: /dev/nvme0n1p1
        Ebs:
          DeleteOnTermination: true
          VolumeSize: 29
      Tags:
        - Key: Name
          Value: !Sub Capstone-${ID}

